Weffc++: disable copying for impl. class
The error message

WPXPropertyList.cpp:198:7: error: 'class WPXMapIterImpl' has pointer data members [-Werror=effc++]
WPXPropertyList.cpp:198:7: error:   but does not override 'WPXMapIterImpl(const WPXMapIterImpl&)' [-Werror=effc++]
WPXPropertyList.cpp:198:7: error:   or 'operator=(const WPXMapIterImpl&)' [-Werror=effc++]

is a red herring, because the class does not own the pointer. But it
turns out it does not have to be copyable anyway.